<html>
	<head>
		<link rel="stylesheet" href="${url.context}/css/hadoop.css" TYPE="text/css">
	</head>
	
	<body>
	<h1>Hadoop Content Store</h1>
	<p>The file has been retrieved from the Hadoop Distributed File System and can be downloaded 
	by clicking on the following link:
	</p>
	
	<!-- A link to the file on the server will be generated by the controller and ouput in 'uploadStatus' -->
	
	<a href="/alfresco/temp/ed2.png">asdfasd</a>



	</body>
	
</html>